baseURL = 'https://maarkeez.github.io/ddd4d-blog'
languageCode = 'en-us'
title = 'DDD4D'
theme = 'hugo-theme-relearn'

[params]
  linkTitle = "DDD Blog"
  themeVariant = ['auto', 'zen-light', 'zen-dark']
  disableLandingPageButton = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'