baseURL = 'https://maarkeez.github.io/ddd4d-blog'
languageCode = 'en-us'
title = 'DDD4D'
theme = 'hugo-theme-relearn'

[params]
  linkTitle = "DDD Blog"
  themeVariant = ['auto', 'zen-light', 'zen-dark']
  disableLandingPageButton = true
  showVisitedLinks = true
  highlightWrap = false
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[outputs]
  home = ['html', 'rss', 'markdown']
  page = ['html', 'markdown']
  section = ['html', 'rss', 'markdown']
[markup]
  [markup.highlight]
    lineNos = true