baseURL = 'https://maarkeez.github.io/ddd4d-blog'
languageCode = 'en-us'
title = 'DDD4D'
theme = 'hugo-theme-relearn'

[params]
  linkTitle = "DDD Blog"

[caches]
  [caches.images]
    dir = ':cacheDir/images'